# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.8
target-version = "py312"

[lint]
select = [
    "A",
    "ASYNC",
    "B",
    "C",
    "C4",
    "COM",
    "DTZ",
    "E",
    "F",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN001",
    "INP",
    "ISC",
    "LOG",
    "N",
    "N",
    "NPY",
    "PD",
    "PIE",
    "PL",
    "PT",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T10",
    "T20",
    "TRY",
    "UP",
    "W",
#    "ANN", TODO: Uncomment
]
ignore = [
    "B024",
    "B027",
    "B905",
    "C417",
    "C901",
    "DTZ001",
    "DTZ002",
    "DTZ005",
    "DTZ006",
    "E741",
    "F403",
    "G004",
    "ISC001",
    "N818",
    "PD901",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLW0603",
    "PT009",
    "PYI024",
    "Q003",
    "Q004",
    "RET504",
    "S101",
    "S311",
    "S324",
    "S605",
    "S607",
    "SIM108",
    "TRY002",  # TODO: Fix
    "TRY003",
    "TRY004",
    "TRY401",  # TODO: Fix
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = [

]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.flake8-quotes]
inline-quotes = "single"
avoid-escape = false

[lint.isort]
lines-after-imports = 2

[format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
